"""Stable public API for Category Product Map V0.1."""

from .builder_v0_1 import (
    DEFAULT_COMBINATION_DIMENSIONS,
    MAX_COMBINATION_MEMBERSHIPS_PER_PRODUCT,
    CategoryProductMapBuilderV0_1,
)
from .errors import (
    CategoryProductMapError,
    CategoryProductMapSerializationError,
    CategoryProductMapValidationError,
)
from .models import (
    CATEGORY_PRODUCT_MAP_VERSION,
    AnalysisWindow,
    AnalysisWindowStatus,
    AttributeDistribution,
    AttributeValueDistribution,
    CategoryCombinationSegment,
    CategoryMapCoverage,
    CategoryMapDiagnostic,
    CategoryMapSourceEvidence,
    CategoryProductMapRequest,
    CategoryProductMapSnapshot,
    CategoryScope,
    CategoryScopeType,
    DenominatorType,
    DistributionDenominator,
    EvidenceAwareMetric,
    EvidenceAwareMetricStatus,
    ExcludedCategoryProduct,
    IncludedCategoryProduct,
    build_category_scope,
    ratio_text,
    unknown_analysis_window,
)

__all__ = (
    "CATEGORY_PRODUCT_MAP_VERSION",
    "DEFAULT_COMBINATION_DIMENSIONS",
    "MAX_COMBINATION_MEMBERSHIPS_PER_PRODUCT",
    "AnalysisWindow",
    "AnalysisWindowStatus",
    "AttributeDistribution",
    "AttributeValueDistribution",
    "CategoryCombinationSegment",
    "CategoryMapCoverage",
    "CategoryMapDiagnostic",
    "CategoryMapSourceEvidence",
    "CategoryProductMapBuilderV0_1",
    "CategoryProductMapError",
    "CategoryProductMapRequest",
    "CategoryProductMapSerializationError",
    "CategoryProductMapSnapshot",
    "CategoryProductMapValidationError",
    "CategoryScope",
    "CategoryScopeType",
    "DenominatorType",
    "DistributionDenominator",
    "EvidenceAwareMetric",
    "EvidenceAwareMetricStatus",
    "ExcludedCategoryProduct",
    "IncludedCategoryProduct",
    "build_category_scope",
    "ratio_text",
    "unknown_analysis_window",
)
