"""Stable public API for Product Attribute Extraction contracts V0.1."""

from .errors import (
    AttributeEvidenceValidationError,
    AttributeTaxonomyValidationError,
    ProductAttributeContractError,
    ProductAttributeSerializationError,
)
from .models import (
    ATTRIBUTE_CONTRACT_VERSION,
    ATTRIBUTE_EXTRACTION_RULESET_VERSION,
    AllowedAttributeValue,
    AttributeAssertionStatus,
    AttributeCardinality,
    AttributeConfidence,
    AttributeConfidenceLevel,
    AttributeCoverage,
    AttributeDiagnostic,
    AttributeDimension,
    AttributeDimensionDefinition,
    AttributeDimensionRegistry,
    AttributeEvidenceSource,
    AttributeExtractionMethod,
    AttributeExtractionRun,
    AttributeNormalizationRuleType,
    AttributeProfileStatus,
    AttributeResolutionStatus,
    AttributeSourceEvidence,
    AttributeState,
    AttributeUnitRule,
    AttributeValueNormalizationRule,
    AttributeValueType,
    CanonicalAttributeAssertion,
    CanonicalAttributeConflict,
    CanonicalAttributeSlot,
    CanonicalAttributeValue,
    CanonicalProductAttributeProfile,
    ProductGrain,
)
from .registry import (
    ATTRIBUTE_DIMENSION_REGISTRY_V0_1,
    ATTRIBUTE_TAXONOMY_VERSION,
    build_attribute_dimension_registry_v0_1,
)
from .extractors import (
    BULLET_ATTRIBUTE_EXTRACTOR_VERSION,
    DESCRIPTION_ATTRIBUTE_EXTRACTOR_VERSION,
    STRUCTURED_ATTRIBUTE_EXTRACTOR_VERSION,
    TITLE_ATTRIBUTE_EXTRACTOR_VERSION,
    BulletAttributeExtractor,
    DescriptionAttributeExtractor,
    ExtractionBatch,
    StructuredAttributeExtractor,
    TitleAttributeExtractor,
)
from .pipeline import ATTRIBUTE_RULES_ENGINE_VERSION, AttributeExtractionPipeline
from .quantity import (
    ATTRIBUTE_UNIT_NORMALIZER_VERSION,
    AttributeUnitNormalizer,
    DeterministicAttributeUnitNormalizerV0_1,
    NormalizedQuantity,
    QuantityCandidate,
    quantity_candidate_id,
)
from .resolver import ATTRIBUTE_CONFLICT_RESOLVER_VERSION, AttributeConflictResolver


__all__ = (
    "ATTRIBUTE_CONTRACT_VERSION",
    "ATTRIBUTE_EXTRACTION_RULESET_VERSION",
    "ATTRIBUTE_TAXONOMY_VERSION",
    "ATTRIBUTE_DIMENSION_REGISTRY_V0_1",
    "build_attribute_dimension_registry_v0_1",
    "ProductAttributeContractError",
    "ProductAttributeSerializationError",
    "AttributeEvidenceValidationError",
    "AttributeTaxonomyValidationError",
    "AttributeDimension",
    "ProductGrain",
    "AttributeProfileStatus",
    "AttributeState",
    "AttributeResolutionStatus",
    "AttributeExtractionMethod",
    "AttributeAssertionStatus",
    "AttributeConfidenceLevel",
    "AttributeValueType",
    "AttributeEvidenceSource",
    "AttributeCardinality",
    "AttributeNormalizationRuleType",
    "AttributeConfidence",
    "CanonicalAttributeValue",
    "AttributeSourceEvidence",
    "CanonicalAttributeAssertion",
    "CanonicalAttributeConflict",
    "CanonicalAttributeSlot",
    "AttributeExtractionRun",
    "AttributeCoverage",
    "AttributeDiagnostic",
    "AllowedAttributeValue",
    "AttributeValueNormalizationRule",
    "AttributeUnitRule",
    "AttributeDimensionDefinition",
    "AttributeDimensionRegistry",
    "CanonicalProductAttributeProfile",
    "ATTRIBUTE_RULES_ENGINE_VERSION",
    "ATTRIBUTE_UNIT_NORMALIZER_VERSION",
    "ATTRIBUTE_CONFLICT_RESOLVER_VERSION",
    "STRUCTURED_ATTRIBUTE_EXTRACTOR_VERSION",
    "TITLE_ATTRIBUTE_EXTRACTOR_VERSION",
    "BULLET_ATTRIBUTE_EXTRACTOR_VERSION",
    "DESCRIPTION_ATTRIBUTE_EXTRACTOR_VERSION",
    "QuantityCandidate",
    "NormalizedQuantity",
    "AttributeUnitNormalizer",
    "DeterministicAttributeUnitNormalizerV0_1",
    "quantity_candidate_id",
    "ExtractionBatch",
    "StructuredAttributeExtractor",
    "TitleAttributeExtractor",
    "BulletAttributeExtractor",
    "DescriptionAttributeExtractor",
    "AttributeConflictResolver",
    "AttributeExtractionPipeline",
)
