"""Strict isolated Market Report V0.2 analytical contracts through SP-039E.

This package intentionally contains no renderer, delivery, or production-pipeline
integration.
"""

from . import adapters, models
from .version import (
    BUYER_NEED_LINK_CONTRACT_VERSION,
    BUYER_NEED_LINK_SECTION_CONTRACT_VERSION,
    BUYER_NEED_PROJECTION_CONTRACT_VERSION,
    COMPETITOR_DETAIL_RECORD_CONTRACT_VERSION,
    COMPETITOR_DETAIL_SECTION_CONTRACT_VERSION,
    COMPETITOR_FIELD_CONTRACT_VERSION,
    COMPETITOR_SHORTLIST_ITEM_CONTRACT_VERSION,
    COMPETITOR_SHORTLIST_SECTION_CONTRACT_VERSION,
    COMPETITOR_STRUCTURE_CONTRACT_VERSION,
    DISTRIBUTION_CONTRACT_VERSION,
    DISTRIBUTION_SEGMENT_CONTRACT_VERSION,
    MARKET_REPORT_V0_2_FOUNDATION_VERSION,
    MARKET_REPORT_V0_2_VERSION,
    MARKET_SIZE_CONTRACT_VERSION,
    METRIC_CONTEXT_CONTRACT_VERSION,
    PRODUCT_DIRECTION_CONTRACT_VERSION,
    PRODUCT_DIRECTION_SECTION_CONTRACT_VERSION,
    SCOPE_CONTEXT_CONTRACT_VERSION,
    TRUE_COMPETITOR_SET_CONTRACT_VERSION,
    REPORT_CONTEXT_CONTRACT_VERSION,
    OPPORTUNITY_PROJECTION_CONTRACT_VERSION,
    EXECUTIVE_SUMMARY_CONTRACT_VERSION,
    EVIDENCE_REGISTRY_CONTRACT_VERSION,
    SANITIZED_APPENDIX_CONTRACT_VERSION,
    EXTERNAL_INTEGRATIONS_CONTRACT_VERSION,
    REPORT_SNAPSHOT_CONTRACT_VERSION,
)
from .builder import compose_market_report_v0_2
from .validation import market_report_v0_2_from_dict

__all__ = (
    "BUYER_NEED_LINK_CONTRACT_VERSION",
    "BUYER_NEED_LINK_SECTION_CONTRACT_VERSION",
    "BUYER_NEED_PROJECTION_CONTRACT_VERSION",
    "COMPETITOR_STRUCTURE_CONTRACT_VERSION",
    "COMPETITOR_DETAIL_RECORD_CONTRACT_VERSION",
    "COMPETITOR_DETAIL_SECTION_CONTRACT_VERSION",
    "COMPETITOR_FIELD_CONTRACT_VERSION",
    "COMPETITOR_SHORTLIST_ITEM_CONTRACT_VERSION",
    "COMPETITOR_SHORTLIST_SECTION_CONTRACT_VERSION",
    "DISTRIBUTION_CONTRACT_VERSION",
    "DISTRIBUTION_SEGMENT_CONTRACT_VERSION",
    "MARKET_REPORT_V0_2_FOUNDATION_VERSION",
    "MARKET_REPORT_V0_2_VERSION",
    "MARKET_SIZE_CONTRACT_VERSION",
    "METRIC_CONTEXT_CONTRACT_VERSION",
    "PRODUCT_DIRECTION_CONTRACT_VERSION",
    "PRODUCT_DIRECTION_SECTION_CONTRACT_VERSION",
    "SCOPE_CONTEXT_CONTRACT_VERSION",
    "TRUE_COMPETITOR_SET_CONTRACT_VERSION",
    "REPORT_CONTEXT_CONTRACT_VERSION",
    "OPPORTUNITY_PROJECTION_CONTRACT_VERSION",
    "EXECUTIVE_SUMMARY_CONTRACT_VERSION",
    "EVIDENCE_REGISTRY_CONTRACT_VERSION",
    "SANITIZED_APPENDIX_CONTRACT_VERSION",
    "EXTERNAL_INTEGRATIONS_CONTRACT_VERSION",
    "REPORT_SNAPSHOT_CONTRACT_VERSION",
    "compose_market_report_v0_2",
    "market_report_v0_2_from_dict",
    "adapters",
    "models",
)
