"""Version constants for the isolated Market Report V0.2 foundation."""

MARKET_REPORT_V0_2_VERSION = "market-report-v0.2"
MARKET_REPORT_V0_2_FOUNDATION_VERSION = "market-report-v0.2-foundation-v0.1"
METRIC_CONTEXT_CONTRACT_VERSION = "metric-context-envelope-v0.1"
SCOPE_CONTEXT_CONTRACT_VERSION = "scope-context-v0.1"
MARKET_SIZE_CONTRACT_VERSION = "market-size-section-v0.1"
TRUE_COMPETITOR_SET_CONTRACT_VERSION = "true-competitor-set-v0.1"
COMPETITOR_STRUCTURE_CONTRACT_VERSION = "competitor-structure-section-v0.1"


__all__ = (
    "COMPETITOR_STRUCTURE_CONTRACT_VERSION",
    "MARKET_REPORT_V0_2_FOUNDATION_VERSION",
    "MARKET_REPORT_V0_2_VERSION",
    "MARKET_SIZE_CONTRACT_VERSION",
    "METRIC_CONTEXT_CONTRACT_VERSION",
    "SCOPE_CONTEXT_CONTRACT_VERSION",
    "TRUE_COMPETITOR_SET_CONTRACT_VERSION",
)
