"""Version constants for the isolated Market Report V0.2 foundation."""

MARKET_REPORT_V0_2_VERSION = "market-report-v0.2"
MARKET_REPORT_V0_2_FOUNDATION_VERSION = "market-report-v0.2-foundation-v0.1"
METRIC_CONTEXT_CONTRACT_VERSION = "metric-context-envelope-v0.1"
SCOPE_CONTEXT_CONTRACT_VERSION = "scope-context-v0.1"
MARKET_SIZE_CONTRACT_VERSION = "market-size-section-v0.1"
TRUE_COMPETITOR_SET_CONTRACT_VERSION = "true-competitor-set-v0.1"
COMPETITOR_STRUCTURE_CONTRACT_VERSION = "competitor-structure-section-v0.1"
DISTRIBUTION_SEGMENT_CONTRACT_VERSION = "distribution-segment-v0.1"
DISTRIBUTION_CONTRACT_VERSION = "distribution-section-item-v0.1"
COMPETITOR_FIELD_CONTRACT_VERSION = "competitor-field-projection-v0.1"
COMPETITOR_DETAIL_RECORD_CONTRACT_VERSION = "competitor-detail-record-v0.1"
COMPETITOR_DETAIL_SECTION_CONTRACT_VERSION = "competitor-detail-section-v0.1"
BUYER_NEED_PROJECTION_CONTRACT_VERSION = "buyer-need-projection-v0.1"
BUYER_NEED_LINK_CONTRACT_VERSION = "buyer-need-link-v0.1"
BUYER_NEED_LINK_SECTION_CONTRACT_VERSION = "buyer-need-link-section-v0.1"
PRODUCT_DIRECTION_CONTRACT_VERSION = "product-direction-v0.1"
PRODUCT_DIRECTION_SECTION_CONTRACT_VERSION = "product-direction-section-v0.1"
COMPETITOR_SHORTLIST_ITEM_CONTRACT_VERSION = "competitor-shortlist-item-v0.1"
COMPETITOR_SHORTLIST_SECTION_CONTRACT_VERSION = "competitor-shortlist-section-v0.1"
REPORT_CONTEXT_CONTRACT_VERSION = "market-report-context-v0.1"
OPPORTUNITY_PROJECTION_CONTRACT_VERSION = "opportunity-projection-v0.1"
EXECUTIVE_SUMMARY_CONTRACT_VERSION = "executive-summary-section-v0.1"
EVIDENCE_REGISTRY_CONTRACT_VERSION = "evidence-registry-v0.1"
SANITIZED_APPENDIX_CONTRACT_VERSION = "sanitized-appendix-v0.1"
EXTERNAL_INTEGRATIONS_CONTRACT_VERSION = "external-integrations-v0.1"
REPORT_SNAPSHOT_CONTRACT_VERSION = "market-report-snapshot-v0.2-contract-v0.1"


__all__ = (
    "BUYER_NEED_LINK_CONTRACT_VERSION",
    "BUYER_NEED_LINK_SECTION_CONTRACT_VERSION",
    "BUYER_NEED_PROJECTION_CONTRACT_VERSION",
    "COMPETITOR_SHORTLIST_ITEM_CONTRACT_VERSION",
    "COMPETITOR_SHORTLIST_SECTION_CONTRACT_VERSION",
    "COMPETITOR_STRUCTURE_CONTRACT_VERSION",
    "COMPETITOR_DETAIL_RECORD_CONTRACT_VERSION",
    "COMPETITOR_DETAIL_SECTION_CONTRACT_VERSION",
    "COMPETITOR_FIELD_CONTRACT_VERSION",
    "DISTRIBUTION_CONTRACT_VERSION",
    "DISTRIBUTION_SEGMENT_CONTRACT_VERSION",
    "MARKET_REPORT_V0_2_FOUNDATION_VERSION",
    "MARKET_REPORT_V0_2_VERSION",
    "MARKET_SIZE_CONTRACT_VERSION",
    "METRIC_CONTEXT_CONTRACT_VERSION",
    "PRODUCT_DIRECTION_CONTRACT_VERSION",
    "PRODUCT_DIRECTION_SECTION_CONTRACT_VERSION",
    "SCOPE_CONTEXT_CONTRACT_VERSION",
    "TRUE_COMPETITOR_SET_CONTRACT_VERSION",
    "REPORT_CONTEXT_CONTRACT_VERSION",
    "OPPORTUNITY_PROJECTION_CONTRACT_VERSION",
    "EXECUTIVE_SUMMARY_CONTRACT_VERSION",
    "EVIDENCE_REGISTRY_CONTRACT_VERSION",
    "SANITIZED_APPENDIX_CONTRACT_VERSION",
    "EXTERNAL_INTEGRATIONS_CONTRACT_VERSION",
    "REPORT_SNAPSHOT_CONTRACT_VERSION",
)
