"""Public pluggable Provider Connector Foundation V0.1."""

from .base import AdapterBackedProvider, DataProvider
from .base_client import BaseAPIClient
from .errors import ProviderConnectorError, ProviderErrorCode
from .models import (
    CanonicalSelector,
    CapabilityStatus,
    ProviderCapability,
    ProviderConfig,
    ProviderFetchResult,
    ProviderFetchStatus,
    ProviderRequest,
)
from .registry import ProviderCandidate, ProviderRegistry, build_registry
from .resolver import (
    ProviderAttempt,
    ProviderAttemptStatus,
    ProviderResolution,
    ProviderResolver,
)
from .sorftime_v0_1 import SORFTIME_CAPABILITIES, SORFTIME_OPERATIONS, SorftimeProvider
from .sorftime_client import (
    SORFTIME_CONTENT_TYPE,
    SORFTIME_CREDENTIAL_ENV,
    SORFTIME_ORIGIN,
    SorftimeClient,
    SorftimeOperationResult,
    SorftimeUsageEvidence,
    validate_sorftime_origin,
)
from .sorftime_dtos_v0_1 import (
    SORFTIME_AMAZON_US,
    SorftimeAsinKeywordRow,
    SorftimeAsinRequestKeywordRequest,
    SorftimeAsinRequestKeywordResponse,
    SorftimeDomainContext,
    SorftimeKeywordSummary,
    SorftimeMinorUnitEvidence,
    SorftimeOrganicPosition,
    SorftimePageState,
    SorftimeProductAttribute,
    SorftimeProductRequest,
    SorftimeProductRequestData,
    SorftimeProductRequestResponse,
    SorftimeProductRequestWireCapture,
    SorftimeProductVariationRow,
    SorftimeProductVariationsRequest,
    SorftimeProductVariationsResponse,
    SorftimeSalesState,
    SorftimeWireFieldInventory,
    SorftimeWireFieldStatus,
    parse_asin_request_keyword_response,
    parse_product_request_response,
    parse_product_request_wire_response,
    parse_product_variations_response,
    resolve_sorftime_domain,
    sorftime_dto_json,
)
from .transport import (
    BoundedTransientRetryPolicy,
    HttpJsonTransport,
    NoRetryPolicy,
    ProviderCredential,
    ProviderOperation,
    ProviderTransport,
    RetryPolicy,
    TransportRequest,
    TransportResponse,
)
from .xiyou_v0_1 import XIYOU_CAPABILITIES, XIYOU_OPERATIONS, XiYouProvider
from .xiyou_client import XiYouClient, XiyouClient


__all__ = (
    "AdapterBackedProvider",
    "BaseAPIClient",
    "BoundedTransientRetryPolicy",
    "CanonicalSelector",
    "CapabilityStatus",
    "DataProvider",
    "HttpJsonTransport",
    "NoRetryPolicy",
    "ProviderAttempt",
    "ProviderAttemptStatus",
    "ProviderCandidate",
    "ProviderCapability",
    "ProviderConfig",
    "ProviderConnectorError",
    "ProviderCredential",
    "ProviderErrorCode",
    "ProviderFetchResult",
    "ProviderFetchStatus",
    "ProviderOperation",
    "ProviderRegistry",
    "ProviderRequest",
    "ProviderResolution",
    "ProviderResolver",
    "ProviderTransport",
    "RetryPolicy",
    "SORFTIME_CAPABILITIES",
    "SORFTIME_OPERATIONS",
    "SORFTIME_AMAZON_US",
    "SORFTIME_CONTENT_TYPE",
    "SORFTIME_CREDENTIAL_ENV",
    "SORFTIME_ORIGIN",
    "SorftimeAsinKeywordRow",
    "SorftimeAsinRequestKeywordRequest",
    "SorftimeAsinRequestKeywordResponse",
    "SorftimeDomainContext",
    "SorftimeKeywordSummary",
    "SorftimeMinorUnitEvidence",
    "SorftimeOrganicPosition",
    "SorftimePageState",
    "SorftimeProductAttribute",
    "SorftimeProductRequest",
    "SorftimeProductRequestData",
    "SorftimeProductRequestResponse",
    "SorftimeProductRequestWireCapture",
    "SorftimeProductVariationRow",
    "SorftimeProductVariationsRequest",
    "SorftimeProductVariationsResponse",
    "SorftimeProvider",
    "SorftimeClient",
    "SorftimeOperationResult",
    "SorftimeSalesState",
    "SorftimeWireFieldInventory",
    "SorftimeWireFieldStatus",
    "SorftimeUsageEvidence",
    "TransportRequest",
    "TransportResponse",
    "XIYOU_CAPABILITIES",
    "XIYOU_OPERATIONS",
    "XiYouProvider",
    "XiYouClient",
    "XiyouClient",
    "build_registry",
    "parse_asin_request_keyword_response",
    "parse_product_request_response",
    "parse_product_request_wire_response",
    "parse_product_variations_response",
    "resolve_sorftime_domain",
    "sorftime_dto_json",
    "validate_sorftime_origin",
)
